### ISSUE TITLE
Update loop

### ISSUE THREAD

**Issue by lbrink** [lucaapp/security-concept#19]
Moin,

Beim ersten Öffnen der App wurde ich in einer Update-Schleife gefangen.

Nach Eingabe aller Kontaktdaten und Bestätigung dieser per Button wurde ich auf die Hauptseite geleitet. Von dort bin ich auf "App Details" gegangen und habe die Kameraberechtigung gesetzt.
Dann bin ich zurück zur Hauptseite. Welchen der beiden Buttons ich dazu genutzt habe, weiß ich leider nicht mehr.
Einen weiteren Klick im 3P-Menü habe ich noch gemacht, aber abgebrochen, weil sich eine Website öffnen wollte.
Zurück auf der Hauptseite habe ich aus unklaren Gründen einfach mal den Android-Zurück-Button geklickt.
Dann war ich wieder in der Kontaktdatenerfassung. Nach Klick auf "Update" bin ich aber darin geblieben.
Nochmaliges Klicken hat mich immer wieder zu dieser Seite gebracht. Beenden der App und Neustart hat geholfen.
Erwartetes Verhalten war, nach Klick auf "Update" auf die Hauptseite zu gelangen.

Gruß und Danke für die App,
Lars

**Comment by reneme** [comment]
Hallo Lars,

danke für dein Feedback. Ich habe die Anfrage an unsere Entwickler weitergeleitet.
Beim nächsten Mal wende dich bitte direkt an: hello@luca-app.de
Das Forum hier ist eher für die Diskussion rund um das Sicherheitskonzept von Luca gedacht.

Grüße aus Berlin,
René

**Comment by lbrink** [comment]
Hallo René,

danke für's Weiterleiten.
An eine unspezifische E-Mail-Adresse würde ich aber keinen Bugreport senden,
zu groß die Gefahr, dass die Arbeit umsonst war.
Also keine weiteren Reports von mir, bis es für die App einen eigenen Issue-Tracker gibt.

Gruß,
Lars
