### ISSUE TITLE
Webapp uses wrong format for dates

### ISSUE THREAD

**Issue by rvnstn** [lucaapp/security-concept#25]
The webapp uses 'dd.mm.yyyy' as formatstring for dates with momentjs. This results in loading the current daily key every minute. To fix this the string should be 'DD.MM.YYYY'. See https://momentjs.com/docs/#/displaying/

**Comment by reneme** [comment]
Thanks for the remark. I'll forward this to the developers.

**Comment by rvnstn** [comment]
Fixed in current Webapp version.
