### ISSUE TITLE
Scanner ids should not be public

### ISSUE THREAD

**Issue by rvnstn** [lucaapp/security-concept#28]
Scanners currently share the same id as the location. They expose the current and total checkins (Maybe more?). Scanners should have their own secret id only visible to the operator.

**Comment by reneme** [comment]
Thank you for pointing this out. We're aware of this issue and are working on a fix. Scanner IDs that are exposed in a venue QR code won't be able to access the check-in counts of the venue soon.

**Comment by rvnstn** [comment]
Detailed prove here: https://twitter.com/sand1drn/status/1379134549775515656

**Comment by rvnstn** [comment]
Fixed on 7.4.2021/8.4.2021. Closed.
