### ISSUE TITLE
Missing licence information in 2.1ae68762.chunk.js.LICENSE.txt

### ISSUE THREAD

**Issue by rvnstn** [lucaapp/security-concept#37]
Please include all licence informations in https://app.luca-app.de/webapp/static/js/2.1ae68762.chunk.js.LICENSE.txt
At least a licence info for the used Ascii85/Base85 implementation is missing.

Regards
Tobias

**Comment by rvnstn** [comment]
Now mentioned in https://app.luca-app.de/webapp/licenses-full.txt

**Comment by philipp-berger** [comment]
Thanks for taking care of the issue; the licence generator plugin is unfortunately broken, therefore the attribution is placed in an external file
